#!/bin/sh

DATADIR=${1} #Specify data directory of interest
STRING=${2} #Specify the string of interest
NAME_OUT_FILE=${3} #Specify the name of the outfile

echo ""
echo ""
echo "Concatenating files in ${DATADIR} with string ${STRING}"
echo ""
echo ""


for datafile in `ls ${DATADIR}`
do
  if [[ $datafile =~ $STRING ]] #If the name of the datafile contains the string
  then
    echo "Datafile with ${STRING} found!"
    echo "Processing ${datafile}"
    # echo "Fill in headers here, separated by delimeter" > ${NAME_OUT_FILE}
    tail +2 ${datafile} >> ${NAME_OUT_FILE} #Cat contents of file except the header to current position in outfile
  fi
done
